[pytest]
minversion = 2.0
norecursedirs = .git
testpaths = icepyx/core icepyx/test
python_files = *.py
addopts = --cov=./ --doctest-modules
doctest_optionflags = NORMALIZE_WHITESPACE NUMBER
markers =
    downloads_data: test downloads data from Harmony (deselect with '-m "not downloads_data"')
