@startuml
title **icepyx Class Diagram** <img: ../_static/icepyx_v2_oval_tiny-uml.PNG>

class Icesat2Data {
    reqparams
    extent_type
    subsetparams
 '   _subsetparams
 '   _version
    file_vars
 '   _cust_options
    start_time
    dates 
    dataset_version
    granules 
 '   _granules
    spatial_extent
 '   _session
 '   _about_dataset
 '   _dset 
 '   _file_vars
    CMRparams
 '   _CMRparams
    dataset 
    order_vars
 '   _start 
 '   _order_vars
    end_time
 '   _source
    subsetparams()
    avail_granules()
    order_granules()
    download_granules()
    visualize_spatial_extent()
    dataset_all_info()
    dataset_summary_info()
    show_custom_options()
    latest_version()
    earthdata_login()
}
class Earthdata {
    uid: string
    email: string
    session
    pswd
    capability_url
    login()
'    _start_session()
}

class Granules {
    orderIDS
 '   _session 
 '   files 
    avail 
    get_avail()
    place_order()
    download()
}

class Variables {
'    _vartype
'    _session
    dataset
    wanted
'    _version
    source
'    _avail
    append()
    avail()
    remove()
'    _check_valid_lists()
'    _iter_paths()
'    _get_sum_varlist()
}


package "ICESat-2 Reference (is2ref)" {
    class about_dataset{

    }
    hide about_dataset circle
    
 '   class _validate_dataset {

 '   }
 '   hide _validate_dataset circle

 '   class _get_custom_options {

 '   }
 '   hide _get_custom_options circle
}

package "Validation (val)" {
    class dset_version {

    }
    hide dset_version circle

    class temporal {

    }
    hide temporal circle

    class spatial {

    }
    hide spatial circle
}

'Try not using a package to help with layout (didn't change anything)
' class APIformatting.build_reqconfig_params {

' }
' hide APIformatting.build_reqconfig_params circle

' class APIformatting.build_CMR_params {

' }
' hide APIformatting.build_CMR_params circle

package "Format for API (apifmt)" {
 '   class _fmt_temporal {

 '   }
 '   hide _fmt_temporal circle

 '   class _fmt_spatial {

 '   }
 '   hide _fmt_spatial circle

 '   class  _fmt_var_subset_list {

 '   }
 '   hide  _fmt_var_subset_list circle

    class combine_params {

    }
    hide combine_params circle

    class Parameters {
    partype 
 '   _reqtype
 '   _fmted_keys
    poss_keys
 '   _fmted_keys
 '   _poss_keys
 '   _get_possible_keys()
 '   _check_valid_keys()
    check_req_values()
    check_values()
    build_params()
    }
}


Icesat2Data *-left- Granules 
Icesat2Data *-right- Variables 

''Icesat2Data -right-> about_dataset : is2ref.about_dataset
''Icesat2Data -right-> _get_custom_options : is2ref._get_custom_options
''Icesat2Data -right-> _validate_dataset : is2ref._validate_dataset
Icesat2Data -right-> "ICESat-2 Reference (is2ref)"

Icesat2Data -right-> "Validation (val)"
''Icesat2Data --> dset_version : val.dset_version
''Icesat2Data --> spatial : val.spatial
''Icesat2Data --> temporal: val.temporal

Icesat2Data -left-> "Format for API (apifmt)"
''Icesat2Data --> build_CMR_params: apifmt.build_CMR_params
''Icesat2Data -->  build_reqconfig_params : apifmt.build_reqconfig_params
'' Icesat2Data -left-> APIformatting

Icesat2Data .down. Earthdata

' Variables -down-> _get_custom_options

'' Granules -[hidden]- APIformatting
'' Earthdata -[hidden]- APIformatting
Granules -[hidden]- "Format for API (apifmt)"
Earthdata -[hidden]- "Format for API (apifmt)"
"ICESat-2 Reference (is2ref)" -[hidden]- "Validation (val)"
@enduml