name: Run linters on PRs

on:
  pull_request:
    branches:
      - development
      - main

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # Use the Ruff linter to annotate code style / best-practice issues
      # NOTE: More config provided in pyproject.toml
      - name: Lint and annotate PR
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0
